name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, edited]
  schedule:
    - cron: "15 0 */7 * *"

jobs:
  build:
    name: Build plugins
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Download AMXX && ReAPI and unpacking
        env:
          AMXMODX: "1.9"
          REAPI: "5.19.0.211"
        run: |
          curl -s https://www.amxmodx.org/amxxdrop/$AMXMODX/$(curl https://www.amxmodx.org/amxxdrop/$AMXMODX/amxmodx-latest-base-linux) -# | tar xz
          curl -OL https://github.com/s1lentq/reapi/releases/download/$REAPI/reapi_$REAPI-dev.zip -#
          unzip reapi_*-dev.zip && rm reapi_*-dev.zip
          cd addons/amxmodx && rm scripting/*.sma && rm plugins/*.amxx
          cd scripting && chmod +x amxxpc32.so && chmod +x compile.sh && chmod +x amxxpc
          cd ../../../
          mkdir _compiler && cp -Rf addons/amxmodx/scripting/* _compiler

      - name: Declare SHA & branch
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Compile plugins AMXX Version
        run: |
          SHA=${{ steps.vars.outputs.sha_short }}

          OUTPUT_DIR="_output"
          mkdir $OUTPUT_DIR
          cp -Rf ./cstrike/addons/amxmodx/* $OUTPUT_DIR
          cd $OUTPUT_DIR

          amxxpc="_compiler/amxxpc"
          amxxpc=$(cd $(dirname $amxxpc); pwd)/$(basename $amxxpc);

          ls

          cd _compiler

          find * -name "*.sma" \
            -exec echo -e "\n\n> Compile {} <" \;\
            -exec ${amxxpc} {} \
              CA_VERSION=$SHA \
              -iinclude \
              -o../plugins/{} \
            \;

      - name: Archieve
        run: |
          tar -czpf ChatAdditions-${{ steps.vars.outputs.sha_short }}.tar.gz addons/*

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ChatAdditions-${{ steps.vars.outputs.sha_short }}.tar.gz
          path: ${{github.workspace}}/addons/
